import { z } from 'zod';
import { ConceptSchema, type Concept } from '../schemas';

// Content is data. It is validated when this module loads, so bad content fails fast.
const RAW: z.input<typeof ConceptSchema>[] = [
  {
    id: 'game-loop',
    name: 'Game loop',
    plain: 'The game repeats the same steps again and again: read input, update the world, draw the picture.',
    technical: 'Game loop',
    mechanism: 'Every pass through the loop is a frame. The loop runs as fast as the screen and the machine allow.',
    district: 'systems',
  },
  {
    id: 'delta-time',
    name: 'Delta time',
    plain: 'The time since the last frame. Movement uses it so a fast computer and a slow one move the same distance per second.',
    technical: 'Delta time',
    mechanism: 'Speed times delta time gives the distance moved this frame.',
    district: 'systems',
  },
  {
    id: 'fixed-timestep',
    name: 'Fixed timestep',
    plain: 'The physics advances in equal small steps, no matter how fast the screen draws.',
    technical: 'Fixed timestep',
    mechanism: 'Time is collected in an accumulator. The simulation runs one fixed step each time a full step of time has built up, so results do not depend on frame rate.',
    district: 'systems',
    related: [{ id: 'game-loop', relation: 'depends_on' }],
  },
  {
    id: 'gravity',
    name: 'Gravity',
    plain: 'Things without support fall down, and they keep speeding up while they fall.',
    technical: 'Gravity',
    mechanism: 'Each step, the downward velocity grows by gravity times delta time. The position then moves by the new velocity.',
    district: 'physics',
    related: [{ id: 'fixed-timestep', relation: 'depends_on' }],
  },
  {
    id: 'collider',
    name: 'Collider',
    plain: 'An invisible shape that tells the game where something is solid.',
    technical: 'Collider',
    mechanism: 'A collider is a geometric shape attached to a body. The physics engine uses colliders, not the visible mesh, to decide what blocks movement.',
    district: 'physics',
    related: [{ id: 'rigid-body', relation: 'depends_on' }],
  },
  {
    id: 'rigid-body',
    name: 'Rigid body',
    plain: 'Something the physics engine moves and reacts to.',
    technical: 'Rigid body',
    mechanism: 'A rigid body has mass and velocity and keeps its shape while it moves. Colliders attach to it. A fixed body never moves.',
    district: 'physics',
  },
  {
    id: 'collision',
    name: 'Collision',
    plain: 'Two solid things touch, and the game has to decide what happens next.',
    technical: 'Collision detection',
    mechanism: 'Each step, the engine finds which shapes overlap, then pushes them apart or reports the contact.',
    district: 'physics',
    related: [{ id: 'collider', relation: 'depends_on' }],
  },
  {
    id: 'broad-phase',
    name: 'Broad phase',
    plain: 'A quick first check that throws away pairs of objects that are far apart.',
    technical: 'Broad phase',
    mechanism: 'Simple boxes around each shape are compared cheaply. Only pairs whose boxes overlap move on to the exact test.',
    district: 'physics',
    related: [{ id: 'narrow-phase', relation: 'causes' }],
  },
  {
    id: 'narrow-phase',
    name: 'Narrow phase',
    plain: 'The exact check, run only on the few pairs that might really touch.',
    technical: 'Narrow phase',
    mechanism: 'The exact shapes are tested against each other to find the real contact points and how deep they overlap.',
    district: 'physics',
  },
  {
    id: 'pbr',
    name: 'PBR',
    plain: 'A way to make materials look real by describing how they react to light, not just what colour they are.',
    technical: 'PBR (physically based rendering)',
    mechanism: 'A material is described by a few physical properties, such as base colour, roughness, and metalness. The same properties give believable results under any light.',
    district: 'graphics',
  },
  {
    id: 'roughness',
    name: 'Roughness',
    plain: 'How smooth or rough a surface is. Smooth surfaces show a sharp shine. Rough surfaces spread the light out.',
    technical: 'Roughness',
    mechanism: 'Roughness widens the specular highlight. At 0 the highlight is a sharp point. At 1 it is spread almost evenly.',
    district: 'graphics',
    related: [{ id: 'pbr', relation: 'depends_on' }],
  },
  {
    id: 'metalness',
    name: 'Metalness',
    plain: 'Whether a surface behaves like metal. Metals reflect their surroundings and tint the reflections with their colour.',
    technical: 'Metalness',
    mechanism: 'At 1 the surface has no diffuse colour and its colour comes only from reflections. At 0 it behaves like plastic or paint.',
    district: 'graphics',
    related: [{ id: 'environment-map', relation: 'depends_on' }],
  },
  {
    id: 'environment-map',
    name: 'Environment map',
    plain: 'A picture of the surroundings that a shiny surface can reflect.',
    technical: 'Environment map',
    mechanism: 'The renderer looks up the reflected direction in a pre-filtered map of the surroundings. Without a map, shiny and metal surfaces have nothing to reflect.',
    district: 'graphics',
  },
  {
    id: 'draw-call',
    name: 'Draw call',
    plain: 'One request from the game to the graphics card to draw something. Many small requests can slow the frame down.',
    technical: 'Draw call',
    mechanism: 'Each mesh with its own material usually costs a separate draw call. The CPU spends time preparing each call, so the total cost grows with the number of calls.',
    district: 'performance',
  },
  {
    id: 'instancing',
    name: 'Instancing',
    plain: 'Draw many copies of the same shape with one request, giving each copy its own position.',
    technical: 'Instancing',
    mechanism: 'One geometry and one material are sent once, along with a list of transforms. The GPU draws every copy in a single call.',
    district: 'performance',
    related: [{ id: 'draw-call', relation: 'mitigates' }],
  },
  {
    id: 'frame-time',
    name: 'Frame time',
    plain: 'How long one frame takes. Lower is smoother. At 60 frames per second you have about 16.7 milliseconds per frame.',
    technical: 'Frame time',
    mechanism: 'Frames per second is the inverse of frame time. Frame time is the sum of CPU work and any GPU work that the CPU has to wait for.',
    district: 'performance',
  },
  {
    id: 'restitution',
    name: 'Restitution',
    plain: 'How bouncy something is. A value of 1 bounces back to the same height. A value of 0 does not bounce at all.',
    technical: 'Restitution',
    mechanism: 'When two surfaces collide, the bounce speed is the impact speed times the restitution of the pair.',
    district: 'physics',
    related: [{ id: 'collision', relation: 'depends_on' }],
  },
  {
    id: 'friction',
    name: 'Friction',
    plain: 'How much two surfaces resist sliding past each other. High friction grips. Low friction slides.',
    technical: 'Friction',
    mechanism: 'The engine limits the sideways impulse at each contact to the friction coefficient times the push into the surface.',
    district: 'physics',
    related: [{ id: 'collision', relation: 'depends_on' }],
  },
  {
    id: 'raycast',
    name: 'Raycast',
    plain: 'Shoot an invisible line and ask what it hits first.',
    technical: 'Raycast',
    mechanism: 'The engine walks the line through the physics world and returns the nearest shape it crosses, with the distance to it.',
    district: 'physics',
    related: [{ id: 'collider', relation: 'depends_on' }],
  },
  {
    id: 'fsm',
    name: 'Finite state machine',
    plain: 'An NPC is always in one mode, such as patrol, chase, or flee. Simple rules decide when it switches.',
    technical: 'FSM (finite state machine)',
    mechanism: 'A set of states plus transitions. Each frame the machine checks the rules for the current state and moves to a new state only when a rule fires.',
    district: 'ai',
  },
  {
    id: 'utility-ai',
    name: 'Utility AI',
    plain: 'Give every choice a score, then pick the best one. The scores can change smoothly as the world changes.',
    technical: 'Utility AI',
    mechanism: 'Each option has a function that maps the world to a number. The agent picks the option with the highest score.',
    district: 'ai',
    related: [{ id: 'fsm', relation: 'alternative' }],
  },
  {
    id: 'animation-state-machine',
    name: 'Animation state machine',
    plain: 'The character is always in one animation state, such as idle or walk. Rules move it from one state to the next.',
    technical: 'Animation state machine',
    mechanism: 'Each state plays a pose or a clip. Transitions are triggered by inputs such as speed, whether the character is on the ground, or a button press.',
    district: 'animation',
    related: [{ id: 'fsm', relation: 'depends_on' }],
  },
  {
    id: 'crossfade',
    name: 'Crossfade',
    plain: 'Smoothly mix from one pose into the next instead of snapping.',
    technical: 'Crossfade (blend)',
    mechanism: 'Each joint angle is interpolated between the old and new values over time. A blend weight rises from 0 to 1.',
    district: 'animation',
    related: [{ id: 'animation-state-machine', relation: 'depends_on' }],
  },
  {
    id: 'locomotion',
    name: 'Locomotion',
    plain: 'The movement of a character on its feet: standing, walking, running, jumping, and landing.',
    technical: 'Locomotion',
    mechanism: 'A group of states driven by speed and ground contact. The limb swing rate follows the speed.',
    district: 'animation',
  },
  {
    id: 'ecs',
    name: 'Entity component system',
    plain: 'Things in the game are just IDs. Their data is stored as separate parts, and separate functions do the work.',
    technical: 'ECS (entity component system)',
    mechanism: 'Entities are IDs, components are plain data, and systems loop over the entities that have the components they need.',
    district: 'systems',
    related: [{ id: 'data-driven-design', relation: 'alternative' }],
  },
  {
    id: 'entity',
    name: 'Entity',
    plain: 'One thing in the game, such as a projectile or a target. It is only an ID.',
    technical: 'Entity',
    mechanism: 'An entity is a number that other data attaches to. It has no behaviour of its own.',
    district: 'systems',
    related: [{ id: 'ecs', relation: 'depends_on' }],
  },
  {
    id: 'component',
    name: 'Component',
    plain: 'One piece of data about an entity, such as where it is or how fast it moves.',
    technical: 'Component',
    mechanism: 'A component is a plain record. Systems read and write components and never change the entity directly.',
    district: 'systems',
    related: [{ id: 'ecs', relation: 'depends_on' }],
  },
  {
    id: 'system',
    name: 'System',
    plain: 'A small job that runs over all the things that have the data it needs, such as moving everything with a speed.',
    technical: 'System',
    mechanism: 'A system is a function that queries for entities with certain components and updates them once per step.',
    district: 'systems',
    related: [{ id: 'component', relation: 'depends_on' }],
  },
  {
    id: 'object-pool',
    name: 'Object pool',
    plain: 'Keep used things in a box and reuse them, instead of creating and destroying a new one every time.',
    technical: 'Object pool',
    mechanism: 'Released objects go into a free list. The next request takes one from the list, which avoids allocation and garbage collection.',
    district: 'systems',
  },
  {
    id: 'event-bus',
    name: 'Event bus',
    plain: 'A place where one part of the game announces something, and any other part can listen without knowing about it.',
    technical: 'Event bus',
    mechanism: 'Systems emit typed events. Listeners subscribe by type. Emitters and listeners never reference each other.',
    district: 'systems',
  },
  {
    id: 'data-driven-design',
    name: 'Data-driven design',
    plain: 'Describe a thing with data, such as a list of components, and let general code build it.',
    technical: 'Data-driven design',
    mechanism: 'Entity recipes are plain objects. New content is added by writing data, not new code paths.',
    district: 'systems',
  },
  {
    id: 'latency',
    name: 'Latency',
    plain: 'The delay between doing something and other players seeing it.',
    technical: 'Latency',
    mechanism: 'Latency is the one-way travel time of a message. Round-trip time is about twice that, and it is what a player feels when waiting for the server to answer.',
    district: 'multiplayer',
  },
  {
    id: 'snapshot',
    name: 'Snapshot',
    plain: 'A picture of the whole game state at one moment, sent from the server to every player.',
    technical: 'Snapshot',
    mechanism: 'The server sends positions and the last input it processed for each player. Clients use it to correct themselves.',
    district: 'multiplayer',
  },
  {
    id: 'client-prediction',
    name: 'Client prediction',
    plain: 'Move your own character right away, before the server confirms it, so the game feels responsive.',
    technical: 'Client-side prediction',
    mechanism: 'The client applies its own inputs with the same rules as the server, and keeps the inputs until the server acknowledges them.',
    district: 'multiplayer',
    related: [{ id: 'reconciliation', relation: 'depends_on' }],
  },
  {
    id: 'reconciliation',
    name: 'Reconciliation',
    plain: 'When the server disagrees with your prediction, go back to the server position and replay your unconfirmed moves.',
    technical: 'Server reconciliation',
    mechanism: 'On each snapshot the client resets to the server state, removes acknowledged inputs, and re-applies the remaining inputs on top.',
    district: 'multiplayer',
  },
  {
    id: 'interpolation',
    name: 'Interpolation',
    plain: 'Show other players slightly in the past, blending between two known positions, so their movement looks smooth.',
    technical: 'Interpolation',
    mechanism: 'Other entities are drawn at a delayed time between two buffered snapshots. A larger delay is smoother but more out of date.',
    district: 'multiplayer',
  },
  {
    id: 'webgpu-constraint',
    name: 'WebGPU',
    plain: 'A newer way for web pages to use the graphics card directly.',
    technical: 'WebGPU',
    mechanism: 'Compared with WebGL, it has better compute support and lower driver overhead. Browser support is still uneven, so a fallback is needed.',
    district: 'web',
  },
  {
    id: 'web-workers',
    name: 'Web Worker',
    plain: 'Run heavy code on a second thread so the screen does not freeze.',
    technical: 'Web Worker',
    mechanism: 'Workers have their own event loop and communicate by messages. They cannot touch the page directly.',
    district: 'web',
  },
  {
    id: 'shared-array-buffer',
    name: 'SharedArrayBuffer',
    plain: 'Memory that several threads can read and write at once.',
    technical: 'SharedArrayBuffer',
    mechanism: 'Browsers only enable it on pages that are cross-origin isolated, using specific response headers. Without them the feature is missing.',
    district: 'web',
  },
  {
    id: 'game-feel',
    name: 'Game feel',
    plain: 'How a game feels to touch. Small feedback effects make an action feel heavier or lighter.',
    technical: 'Game feel (juice)',
    mechanism: 'Feedback such as shake, pauses, and particles is added on top of the same underlying action. The action is unchanged; the presentation changes.',
    district: 'feel',
  },
  {
    id: 'hit-stop',
    name: 'Hit stop',
    plain: 'A very short freeze when something is hit. It makes the hit feel solid.',
    technical: 'Hit stop (hit pause)',
    mechanism: 'For a few frames, the animation of the hit object is paused while the hit is shown. The rest of the scene may keep running.',
    district: 'feel',
  },
  {
    id: 'screen-shake',
    name: 'Screen shake',
    plain: 'The camera jolts after a big hit, then settles.',
    technical: 'Camera shake',
    mechanism: 'An offset is added to the camera position. The offset starts large and decays to zero. It is added after the normal camera movement so it does not accumulate.',
    district: 'feel',
  },
  {
    id: 'recoil',
    name: 'Recoil',
    plain: 'The thing you hit or fire is pushed back, then comes back.',
    technical: 'Recoil',
    mechanism: 'A fast negative offset that decays exponentially, so the object jumps back and eases into place.',
    district: 'feel',
  },
  {
    id: 'procedural-generation',
    name: 'Procedural generation',
    plain: 'Let a formula make the world instead of drawing every part by hand.',
    technical: 'Procedural generation',
    mechanism: 'A deterministic function of coordinates and a seed produces terrain, objects, or both. Changing the function or seed changes the world.',
    district: 'world',
  },
  {
    id: 'seed',
    name: 'Seed',
    plain: 'A number that picks one world out of all the possible ones.',
    technical: 'Seed',
    mechanism: 'The generator uses the seed as an input to its hash. The same seed and the same coordinates always return the same value.',
    district: 'world',
    related: [{ id: 'procedural-generation', relation: 'depends_on' }],
  },
  {
    id: 'world-streaming',
    name: 'World streaming',
    plain: 'Load only the parts of a big world near the player, and drop the rest.',
    technical: 'World streaming',
    mechanism: 'The world is divided into cells. Each frame the cells within a radius of the player are kept loaded; the others are released.',
    district: 'world',
    related: [{ id: 'procedural-generation', relation: 'mitigates' }],
  },
];

export const CONCEPTS: Concept[] = z.array(ConceptSchema).parse(RAW);
export const CONCEPT_BY_ID = new Map<string, Concept>(CONCEPTS.map((c) => [c.id, c]));
