import { z } from 'zod';
import { ConceptSchema, type Concept } from '../schemas';

// Content is data. It is validated when this module loads, so bad content fails fast.
const RAW: z.input<typeof ConceptSchema>[] = [
  {
    id: 'game-loop',
    name: 'Game loop',
    plain: 'The game repeats the same steps again and again: read input, update the world, draw the picture.',
    technical: 'Game loop',
    mechanism: 'Every pass through the loop is a frame. The loop runs as fast as the screen and the machine allow.',
    district: 'systems',
  },
  {
    id: 'delta-time',
    name: 'Delta time',
    plain: 'The time since the last frame. Movement uses it so a fast computer and a slow one move the same distance per second.',
    technical: 'Delta time',
    mechanism: 'Speed times delta time gives the distance moved this frame.',
    district: 'systems',
  },
  {
    id: 'fixed-timestep',
    name: 'Fixed timestep',
    plain: 'The physics advances in equal small steps, no matter how fast the screen draws.',
    technical: 'Fixed timestep',
    mechanism: 'Time is collected in an accumulator. The simulation runs one fixed step each time a full step of time has built up, so results do not depend on frame rate.',
    district: 'systems',
    related: [{ id: 'game-loop', relation: 'depends_on' }],
  },
  {
    id: 'gravity',
    name: 'Gravity',
    plain: 'Things without support fall down, and they keep speeding up while they fall.',
    technical: 'Gravity',
    mechanism: 'Each step, the downward velocity grows by gravity times delta time. The position then moves by the new velocity.',
    district: 'physics',
    related: [{ id: 'fixed-timestep', relation: 'depends_on' }],
  },
  {
    id: 'collider',
    name: 'Collider',
    plain: 'An invisible shape that tells the game where something is solid.',
    technical: 'Collider',
    mechanism: 'A collider is a geometric shape attached to a body. The physics engine uses colliders, not the visible mesh, to decide what blocks movement.',
    district: 'physics',
    related: [{ id: 'rigid-body', relation: 'depends_on' }],
  },
  {
    id: 'rigid-body',
    name: 'Rigid body',
    plain: 'Something the physics engine moves and reacts to.',
    technical: 'Rigid body',
    mechanism: 'A rigid body has mass and velocity and keeps its shape while it moves. Colliders attach to it. A fixed body never moves.',
    district: 'physics',
  },
  {
    id: 'collision',
    name: 'Collision',
    plain: 'Two solid things touch, and the game has to decide what happens next.',
    technical: 'Collision detection',
    mechanism: 'Each step, the engine finds which shapes overlap, then pushes them apart or reports the contact.',
    district: 'physics',
    related: [{ id: 'collider', relation: 'depends_on' }],
  },
  {
    id: 'broad-phase',
    name: 'Broad phase',
    plain: 'A quick first check that throws away pairs of objects that are far apart.',
    technical: 'Broad phase',
    mechanism: 'Simple boxes around each shape are compared cheaply. Only pairs whose boxes overlap move on to the exact test.',
    district: 'physics',
    related: [{ id: 'narrow-phase', relation: 'causes' }],
  },
  {
    id: 'narrow-phase',
    name: 'Narrow phase',
    plain: 'The exact check, run only on the few pairs that might really touch.',
    technical: 'Narrow phase',
    mechanism: 'The exact shapes are tested against each other to find the real contact points and how deep they overlap.',
    district: 'physics',
  },
  {
    id: 'pbr',
    name: 'PBR',
    plain: 'A way to make materials look real by describing how they react to light, not just what colour they are.',
    technical: 'PBR (physically based rendering)',
    mechanism: 'A material is described by a few physical properties, such as base colour, roughness, and metalness. The same properties give believable results under any light.',
    district: 'graphics',
  },
  {
    id: 'roughness',
    name: 'Roughness',
    plain: 'How smooth or rough a surface is. Smooth surfaces show a sharp shine. Rough surfaces spread the light out.',
    technical: 'Roughness',
    mechanism: 'Roughness widens the specular highlight. At 0 the highlight is a sharp point. At 1 it is spread almost evenly.',
    district: 'graphics',
    related: [{ id: 'pbr', relation: 'depends_on' }],
  },
  {
    id: 'metalness',
    name: 'Metalness',
    plain: 'Whether a surface behaves like metal. Metals reflect their surroundings and tint the reflections with their colour.',
    technical: 'Metalness',
    mechanism: 'At 1 the surface has no diffuse colour and its colour comes only from reflections. At 0 it behaves like plastic or paint.',
    district: 'graphics',
    related: [{ id: 'environment-map', relation: 'depends_on' }],
  },
  {
    id: 'environment-map',
    name: 'Environment map',
    plain: 'A picture of the surroundings that a shiny surface can reflect.',
    technical: 'Environment map',
    mechanism: 'The renderer looks up the reflected direction in a pre-filtered map of the surroundings. Without a map, shiny and metal surfaces have nothing to reflect.',
    district: 'graphics',
  },
  {
    id: 'draw-call',
    name: 'Draw call',
    plain: 'One request from the game to the graphics card to draw something. Many small requests can slow the frame down.',
    technical: 'Draw call',
    mechanism: 'Each mesh with its own material usually costs a separate draw call. The CPU spends time preparing each call, so the total cost grows with the number of calls.',
    district: 'performance',
  },
  {
    id: 'instancing',
    name: 'Instancing',
    plain: 'Draw many copies of the same shape with one request, giving each copy its own position.',
    technical: 'Instancing',
    mechanism: 'One geometry and one material are sent once, along with a list of transforms. The GPU draws every copy in a single call.',
    district: 'performance',
    related: [{ id: 'draw-call', relation: 'mitigates' }],
  },
  {
    id: 'frame-time',
    name: 'Frame time',
    plain: 'How long one frame takes. Lower is smoother. At 60 frames per second you have about 16.7 milliseconds per frame.',
    technical: 'Frame time',
    mechanism: 'Frames per second is the inverse of frame time. Frame time is the sum of CPU work and any GPU work that the CPU has to wait for.',
    district: 'performance',
  },
];

export const CONCEPTS: Concept[] = z.array(ConceptSchema).parse(RAW);
export const CONCEPT_BY_ID = new Map<string, Concept>(CONCEPTS.map((c) => [c.id, c]));
